In [2]:
import numpy as np

def Alexandre(l, N, increasing = False):
    if increasing:
        print(np.array([ j** i for j in l for i in range(N)]).reshape(len(l), N))
    else:
        print(np.array([ j** (N-1-i) for j in l for i in range(N)]).reshape(len(l), N))
        
mylst = [1,2,3]
N = 4

Alexandre(np.array(mylst),N)
print('\n\n')
Alexandre(np.array(mylst),N, increasing= True)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]



[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]


# Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:

myvar= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
window = 3
result = []

for i in range(len(myvar)):
    if i != len(myvar)-2:
        result.append((myvar[i]+myvar[i+1]+myvar[i+2])/window)
    else:
        break
result_size = len(myvar)-window+1
print(f'average sequence size: {result_size}')
print(f'result list size: {len(result)}')
for i in range(len(result)):
    print(f'y{i+1} = {result[i]}')

average sequence size: 11
result list size: 11
y1 = 5.0
y2 = 4.666666666666667
y3 = 5.666666666666667
y4 = 6.666666666666667
y5 = 9.666666666666666
y6 = 28.666666666666668
y7 = 49.333333333333336
y8 = 72.66666666666667
y9 = 84.0
y10 = 93.33333333333333
y11 = 116.33333333333333
